[env]
NPM_CONFIG_USERCONFIG = "{{ [xdg_config_home, 'npm', 'npmrc'] | join_path }}"

[settings.npm]
package_manager = "pnpm"

[tools]
aube = { version = "latest" }
node = { version = "lts" }
pnpm = { version = "latest" }
bun = { version = "latest" }
deno = { version = "latest" }
