[env]
NPM_CONFIG_USERCONFIG = "{{ [xdg_config_home] | concat(with='npm') | concat(with='npmrc') | join_path }}"

[settings.npm]
bun = true

[tools]
node = { version = "latest" }
pnpm = { version = "latest" }
bun = { version = "latest" }
deno = { version = "latest" }
