source completions/cargo_completions.nu
source completions/cargo_make_completions.nu
source completions/curl_completions.nu
source completions/eza_completions.nu
source completions/gh_completions.nu
source completions/npm_completions.nu
source completions/pnpm_completions.nu
source completions/rustup_completions.nu
source completions/tar_completions.nu
source completions/tcpdump_completions.nu
