# エディターの補完を設定スキーマに合わせて取得
"$schema" = 'https://starship.rs/config-schema.json'

# シェルのプロンプトの間に空行を挿入する
add_newline = true
command_timeout = 3600000
scan_timeout = 500

format = "$shell$directory$all$time$cmd_duration$line_break$character"

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

# パッケージモジュールを無効化することでプロンプトを完全に非表示にする
[package]
disabled = true

[directory]
truncation_length = 100
truncate_to_repo = false

[battery]
disabled = true

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"

[docker_context]
format = "via [🐋 $context]($style) "
style = "bold blue"

[time]
disabled = false
format = "[$time]($style) "

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user🌱]($style) "
disabled = true
show_always = true

[shell]
disabled = false
format = '[$indicator]($style) '
style = "white bold"
